name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22.x
      -
        name: build-and-release
        run: |
          CGO_ENABLED=0 GOOS=linux   GOARCH=amd64 go build -o gorun.linux-amd64   ./cmd/gorun 
          CGO_ENABLED=0 GOOS=linux   GOARCH=arm64 go build -o gorun.linux-arm64   ./cmd/gorun 
          CGO_ENABLED=0 GOOS=darwin  GOARCH=amd64 go build -o gorun.darwin-amd64  ./cmd/gorun 
          CGO_ENABLED=0 GOOS=darwin  GOARCH=arm64 go build -o gorun.darwin-arm64  ./cmd/gorun 
          gh release upload ${{ github.ref_name }} gorun.linux-amd64
          gh release upload ${{ github.ref_name }} gorun.linux-arm64
          gh release upload ${{ github.ref_name }} gorun.darwin-amd64
          gh release upload ${{ github.ref_name }} gorun.darwin-arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CGO_ENABLED: 0
